### PR TITLE
fix: parse each language injection region as independent tree

### LINKED ISSUE #2478: [bug] languageInjections: combined ranges produce wrong matches and duplicates
### Please read the FAQ for the bug you encountered.

- [x] I have read the existing FAQ

### ⏯ Playground Link

https://github.com/Dsaquel/ast-grep-issue

### 💻 Code

As discussed in discord before, when using languageInjections, matched regions for the same language are grouped and parsed as a single tree-sitter document instead of independently. This produces invalid ASTs and duplicated results.

### 🙁 Actual behavior

```sh
git clone git@github.com:Dsaquel/ast-grep-issue.git
ast-grep scan
```
produces:
Image

### 🙂 Expected behavior

Image

### Additional information about the issue

ast-grep version: 0.40.5

### PR DESCRIPTION
**Pull request by Dsaquel**
fix #2478

## Summary by CodeRabbit

* **Refactor**
  * Reworked how embedded/injected languages are collected and represented so each injected fragment is reported as its own entry.
  * Improves handling of multiple injection occurrences and ensures injected fragments are consistently included in file analysis, yielding more accurate parsing and tooling for files with embedded languages.

### CODE REVIEW

File: crates/language/src/html.rs [hunk 1]
```diff
@@ -139,7 +139,7 @@ mod test {
 
   fn extract(src: &str) -> HashMap<String, Vec<TSRange>> {
     let root = Html.ast_grep(src);
-    Html.extract_injections(root.root())
+    Html.extract_injections(root.root()).into_iter().collect()
   }
```
[the remark this answers is not in the document]
Comment (Dsaquel) [reply crates/language/src/html.rs]: 956d88738c10

File: crates/cli/src/lang/mod.rs [hunk 2]
```diff
@@ -70,8 +70,14 @@ impl SgLang {
     // TODO: handle injected languages not found
     // e.g vue can inject scss which is not supported by sg
     // we should report an error here
-    let iter = langs.iter().filter_map(|s| SgLang::from_str(s).ok());
-    Some(iter)
+    // Dedup because aliases like "ts" and "typescript" resolve to the same SgLang
+    let mut seen = HashSet::new();
```
Comment (HerringtonDarkholme) [inline crates/cli/src/lang/mod.rs:74]: I think this does not need to be sorted. So a hashset will be good enough

File: crates/cli/src/utils/mod.rs [hunk 3]
```diff
@@ -133,15 +133,12 @@ pub fn filter_file_rule(
   let grep = lang.ast_grep(file_content);
   collect_file_stats(path, lang, configs, trace)?;
   let mut ret = smallvec![grep.clone()];
-  if let Some(injected) = lang.injectable_sg_langs() {
+  if lang.injectable_languages().is_some() {
     let sub_roots = grep.get_injections(|s| SgLang::from_str(s).ok());
-    let inj = injected.filter_map(|l| {
-      let root = sub_roots.iter().find(|d| *d.lang() == l)?;
```
Comment (HerringtonDarkholme) [inline crates/cli/src/utils/mod.rs:139]: yeah, the original implementation looks wrong..

**Review by HerringtonDarkholme — APPROVED** [review]

**Comment by HerringtonDarkholme** [comment]
Thanks! The fix looks awesome

File: crates/cli/src/lang/mod.rs (hunk 2 above)
Comment (Dsaquel) [reply crates/cli/src/lang/mod.rs:74]: You right, just seen you merged the PR i can refact this in another PR. (I have another PR in preparation).

Comment (HerringtonDarkholme) [reply crates/cli/src/lang/mod.rs:74]: no worry, i can push one now

Comment (Dsaquel) [reply crates/cli/src/lang/mod.rs:74]: Just seen, thank you :saluting_face:
