### PR TITLE
    fix: use get_range instead as_slice to handle byte_offset and underlying arry size

### LINKED ISSUE #400: [BUG] replacer does not work in JS napi because wrong byte_offset for multiple node
See https://github.com/ast-grep/ast-grep/blob/main/crates/core/src/replacer.rs#L165-L166

### PR DESCRIPTION
**Pull request by HerringtonDarkholme**
We used to expose underlying binary array of the Source. However, in JavaScript.
    The start_pos is in byte offset.  But underlying binary array can be in u16.
    This pull request changes the interface of source by replacing as_slice with get_range.
    So source can handle this discrepancy gracefully.
    fix #400

Also added test cases.

### CODE REVIEW

File: crates/core/src/match_tree.rs [hunk 1]
```diff
@@ -100,12 +100,18 @@ fn match_multi_nodes_end_non_recursive<'g, 'c, D: Doc + 'c>(
       goal_children.next();
       // goal has all matched
       if goal_children.peek().is_none() {
-        return Some(end);
+        // TODO: handle named and unnamed ellipsis
+        // we need to consume all cand_children to match ellipsis
+        let updated_end = cand_children.last().map(|n| n.range().end).unwrap_or(end);
```
Comment (HerringtonDarkholme) [inline crates/core/src/match_tree.rs:105]: I also found a bug here :(
